---
title: "Assignment 4"
author: "Madeline Berger"
date: "11/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load necessary packages 

library(tidyverse)
library(vcdExtra)
library(kableExtra)
library(RColorBrewer)
library(car)
library(effsize)
library(kableExtra)
```

Read in the CSVs

```{r}


lobster_size <- read_csv("lobster_size_abundance.csv")
lobster_traps <- read_csv("lobster_traps.csv")
```

The lobster_size file needs to be converted to tidyverse format

```{r}

#convert data to tidyverse
lobster_size1 <- as.data.frame(lobster_size)
lobster_size2 <- expand.dft(lobster_size1, freq = "COUNT") %>% 
  select(YEAR, SITE, SIZE)

lobster_traps1 <- as.data.frame(lobster_traps)
lobster_traps2 <- expand.dft(lobster_traps, freq = "TRAPS")
```

```{r}

#Data wrangling into tables and exploratory graphs

lobster_traps_clean <- lobster_traps %>% 
  select(YEAR, MONTH, SITE, TRAPS) %>% 
  count(SITE, YEAR) %>% 
  filter(SITE== "CARP" | SITE== "MOHK" | SITE== "AQUE" | SITE== "NAPL" | SITE== "IVEE") %>% 
  rename(traps = "n")

lobster_abundance <- lobster_size %>% 
  select(YEAR, MONTH, SITE, COUNT) %>% 
  count(SITE, YEAR) %>% 
  filter(SITE== "CARP" | SITE== "MOHK" | SITE== "AQUE" | SITE== "NAPL" | SITE== "IVEE") %>% 
  rename(abundance = "n")


trap_plot <- lobster_traps %>% 
  select(YEAR, MONTH, SITE, TRAPS) %>% 
  filter(SITE== "CARP" | SITE== "MOHK" | SITE== "AQUE" | SITE== "NAPL" | SITE== "IVEE") %>% 
  count(SITE, YEAR) %>% 
  ggplot(aes(x = YEAR, y = n)) +
  geom_line(aes(color=SITE)) +
  theme_classic()


trap_plot
  
```


```{r}

#merge cleaned size and abundance data, graph by site
together <- merge(lobster_traps_clean,lobster_abundance, by = c("SITE", "YEAR")) %>% 
  ggplot(aes(x=traps, y=abundance)) +
  geom_col(aes(fill=SITE))+
  facet_wrap(~SITE, scale = "free")

together

```


4. Proportions of legal lobsters
```{r}

carapace <- lobster_size %>% 
  filter(SIZE != "-99999") %>% 
  select(SITE, SIZE) %>% 
  mutate(Legality = ifelse(SIZE >= 86, "Legal", "Illegal")) %>% 
  count(SITE, Legality) %>% 
  spread(Legality, n) %>% 
  select(-SITE)

rownames(carapace) <- c("AQUE", "CARP", "IVEE", "MOHK", "NAPL")

```

Proprtions of legal groups and table of them:

```{r}
carapace_prop <- prop.table(as.matrix(carapace), 1) %>% 
  round(2)

carapace_prop

carapace_prop_table <- kable(carapace_prop, col.names = c("Illegal","Legal"), align = "c") %>% 
  kable_styling(bootstrap_options = "striped", full_width = F)

carapace_prop_table

```

Chi-square test

```{r}
carapace_x2 <- chisq.test(carapace)
carapace_x2

# X2 = 39.011, df = 4, p value = 6.931e-08
```
The proportion of observed lobsters that were above the legal minimum differed signficantly across all sites ($\chi^2$(`r carapace_x2$parameter`) = `r round(carapace_x2$statistic, 2)`, p value < 0.001).
